name = "isucholar_cfworkers"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-04-13"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

# [secrets]
# APP_SECRET
# POSTGREST_ENDPOINT
# POSTGREST_APIKEY
