name = "isucholar_cfworkers"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-04-10"

# [secrets]
# APP_SECRET
# POSTGREST_ENDPOINT
# POSTGREST_APIKEY
